services:
  localstack:
    image: localstack/localstack:latest
    container_name: hwhub-localstack
    ports:
      - "4566:4566"      # メインエンドポイント
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_HOST=localstack
    volumes:
      - "./localstack/data:/var/lib/localstack"
      - "./localstack/init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: hwhub-mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
