spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwhub_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: hwhub
    password: hwhub
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
logging:
  level:
    "[com.hwhub.backend]": DEBUG
    "[org.mybatis]": DEBUG
    "[org.springframework.security]": DEBUG

hwhub:
  jwt:
    secret: "change-this-to-long-random-secret"

  object-storage:
    bucket: hwhub-dev-file

  aws:
    s3:
      region: ap-northeast-1
      endpoint: http://localhost:4566
      access-key: dummy
      secret-key: dummy
      path-style-access-enabled: true

  auth:
    email-verification:
      enabled: true
      send-mail: true
      token-ttl-minutes: 30
      resend-cooldown-seconds: 60
      max-requests-per-day: 5
      front-base-url: http://localhost:5173
      verify-path: /email-verify

  mail:
    from: no-reply@test.familyapp-hwhub.com
