spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.hwhub.backend.infrastructure.mybatis.generated.entity
  configuration:
    map-underscore-to-camel-case: true

hwhub:
  jwt:
    expiry-millis: 14400000

  object-storage:
    base-path:
      shopping-item: shopping-item
      user-icon: user-icon
    url-ttl-seconds: 600
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
    info:
      enabled: true
  info:
    env:
      enabled: true

# APP_VERSION 環境変数を info に載せる
info:
  app:
    version: ${APP_VERSION:local}