hwhub:
  object-storage:
    bucket: hwhub-dev-file
    base-path:
      shopping-item: shopping-item
      user-icon: user-icon
    url-ttl-seconds: 600

  aws:
    s3:
      region: ap-northeast-1
      endpoint: http://localhost:4566
      access-key: dummy
      secret-key: dummy
      path-style-access-enabled: false
